!     -*- f90 -*-
!     This file is autogenerated with f2py (version:2)
!     It contains Fortran 90 wrappers to fortran functions.

      
      subroutine f2pyinitlocal_kinds(f2pysetupfunc)
      use local_kinds, only : sgl
      use local_kinds, only : dbl
      use local_kinds, only : vshort
      use local_kinds, only : short
      use local_kinds, only : long
      use local_kinds, only : lo
      use local_kinds, only : length
      use local_kinds, only : pi
      use local_kinds, only : pio2
      use local_kinds, only : twopi
      use local_kinds, only : sqrt2
      use local_kinds, only : euler
      use local_kinds, only : pi_d
      use local_kinds, only : pio2_d
      use local_kinds, only : twopi_d
      use local_kinds, only : sqrt2_d
      use local_kinds, only : euler_d
      use local_kinds, only : e
      use local_kinds, only : me
      use local_kinds, only : e0
      use local_kinds, only : c
      use local_kinds, only : zerodbl
      external f2pysetupfunc
      call f2pysetupfunc(sgl,dbl,vshort,short,long,lo,length,pi,pio2,two&
     &pi,sqrt2,euler,pi_d,pio2_d,twopi_d,sqrt2_d,euler_d,e,me,e0,c,zerod&
     &bl)
      end subroutine f2pyinitlocal_kinds

      
      subroutine f2pyinitgmm_f2py_module(f2pysetupfunc)
      use gmm_f2py_module, only : emn
      use gmm_f2py_module, only : expansion_coefficients
      use gmm_f2py_module, only : exyz
      use gmm_f2py_module, only : efar
      use gmm_f2py_module, only : efar_poynting
      use gmm_f2py_module, only : dip_coefficients
      external f2pysetupfunc
      call f2pysetupfunc(emn,expansion_coefficients,exyz,efar,efar_poynt&
     &ing,dip_coefficients)
      end subroutine f2pyinitgmm_f2py_module


