/* File: gmm_pymodule.c
 * This file is auto-generated with f2py (version:2).
 * f2py is a Fortran to Python Interface Generator (FPIG), Second Edition,
 * written by Pearu Peterson <pearu@cens.ioc.ee>.
 * Generation date: Thu Apr 25 08:22:22 2019
 * Do not edit this file directly unless you know what you are doing!!!
 */

#ifdef __cplusplus
extern "C" {
#endif

/*********************** See f2py2e/cfuncs.py: includes ***********************/
#include "Python.h"
#include <stdarg.h>
#include "fortranobject.h"
#include <string.h>
#include <math.h>

/**************** See f2py2e/rules.py: mod_rules['modulebody'] ****************/
static PyObject *gmm_py_error;
static PyObject *gmm_py_module;

/*********************** See f2py2e/cfuncs.py: typedefs ***********************/
typedef char * string;
typedef struct {double r,i;} complex_double;

/****************** See f2py2e/cfuncs.py: typedefs_generated ******************/
/*need_typedefs_generated*/

/********************** See f2py2e/cfuncs.py: cppmacros **********************/
\
#define FAILNULL(p) do {                                            \
    if ((p) == NULL) {                                              \
        PyErr_SetString(PyExc_MemoryError, "NULL pointer found");   \
        goto capi_fail;                                             \
    }                                                               \
} while (0)

#define STRINGMALLOC(str,len)\
    if ((str = (string)malloc(sizeof(char)*(len+1))) == NULL) {\
        PyErr_SetString(PyExc_MemoryError, "out of memory");\
        goto capi_fail;\
    } else {\
        (str)[len] = '\0';\
    }

#define PRINTPYOBJERR(obj)\
    fprintf(stderr,"gmm_py.error is related to ");\
    PyObject_Print((PyObject *)obj,stderr,Py_PRINT_RAW);\
    fprintf(stderr,"\n");

#define pyobj_from_double1(v) (PyFloat_FromDouble(v))
#define rank(var) var ## _Rank
#define shape(var,dim) var ## _Dims[dim]
#define old_rank(var) (PyArray_NDIM((PyArrayObject *)(capi_ ## var ## _tmp)))
#define old_shape(var,dim) PyArray_DIM(((PyArrayObject *)(capi_ ## var ## _tmp)),dim)
#define fshape(var,dim) shape(var,rank(var)-dim-1)
#define len(var) shape(var,0)
#define flen(var) fshape(var,0)
#define old_size(var) PyArray_SIZE((PyArrayObject *)(capi_ ## var ## _tmp))
/* #define index(i) capi_i ## i */
#define slen(var) capi_ ## var ## _len
#define size(var, ...) f2py_size((PyArrayObject *)(capi_ ## var ## _tmp), ## __VA_ARGS__, -1)

#ifdef DEBUGCFUNCS
#define CFUNCSMESS(mess) fprintf(stderr,"debug-capi:"mess);
#define CFUNCSMESSPY(mess,obj) CFUNCSMESS(mess) \
    PyObject_Print((PyObject *)obj,stderr,Py_PRINT_RAW);\
    fprintf(stderr,"\n");
#else
#define CFUNCSMESS(mess)
#define CFUNCSMESSPY(mess,obj)
#endif

#ifndef max
#define max(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef min
#define min(a,b) ((a < b) ? (a) : (b))
#endif
#ifndef MAX
#define MAX(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef MIN
#define MIN(a,b) ((a < b) ? (a) : (b))
#endif

#define STRINGFREE(str) do {if (!(str == NULL)) free(str);} while (0)

#define CHECKSCALAR(check,tcheck,name,show,var)\
    if (!(check)) {\
        char errstring[256];\
        sprintf(errstring, "%s: "show, "("tcheck") failed for "name, var);\
        PyErr_SetString(gmm_py_error,errstring);\
        /*goto capi_fail;*/\
    } else 
#define pyobj_from_complex_double1(v) (PyComplex_FromDoubles(v.r,v.i))
#if defined(PREPEND_FORTRAN)
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F
#else
#define F_FUNC(f,F) _##f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F##_
#else
#define F_FUNC(f,F) _##f##_
#endif
#endif
#else
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F
#else
#define F_FUNC(f,F) f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F##_
#else
#define F_FUNC(f,F) f##_
#endif
#endif
#endif
#if defined(UNDERSCORE_G77)
#define F_FUNC_US(f,F) F_FUNC(f##_,F##_)
#else
#define F_FUNC_US(f,F) F_FUNC(f,F)
#endif

#define STRINGCOPYN(to,from,buf_size)                           \
    do {                                                        \
        int _m = (buf_size);                                    \
        char *_to = (to);                                       \
        char *_from = (from);                                   \
        FAILNULL(_to); FAILNULL(_from);                         \
        (void)strncpy(_to, _from, sizeof(char)*_m);             \
        _to[_m-1] = '\0';                                      \
        /* Padding with spaces instead of nulls */              \
        for (_m -= 2; _m >= 0 && _to[_m] == '\0'; _m--) {      \
            _to[_m] = ' ';                                      \
        }                                                       \
    } while (0)

/* New SciPy */
#define TRYPYARRAYTEMPLATECHAR case NPY_STRING: *(char *)(PyArray_DATA(arr))=*v; break;
#define TRYPYARRAYTEMPLATELONG case NPY_LONG: *(long *)(PyArray_DATA(arr))=*v; break;
#define TRYPYARRAYTEMPLATEOBJECT case NPY_OBJECT: PyArray_SETITEM(arr,PyArray_DATA(arr),pyobj_from_ ## ctype ## 1(*v)); break;

#define TRYPYARRAYTEMPLATE(ctype,typecode) \
        PyArrayObject *arr = NULL;\
        if (!obj) return -2;\
        if (!PyArray_Check(obj)) return -1;\
        if (!(arr=(PyArrayObject *)obj)) {fprintf(stderr,"TRYPYARRAYTEMPLATE:");PRINTPYOBJERR(obj);return 0;}\
        if (PyArray_DESCR(arr)->type==typecode)  {*(ctype *)(PyArray_DATA(arr))=*v; return 1;}\
        switch (PyArray_TYPE(arr)) {\
                case NPY_DOUBLE: *(double *)(PyArray_DATA(arr))=*v; break;\
                case NPY_INT: *(int *)(PyArray_DATA(arr))=*v; break;\
                case NPY_LONG: *(long *)(PyArray_DATA(arr))=*v; break;\
                case NPY_FLOAT: *(float *)(PyArray_DATA(arr))=*v; break;\
                case NPY_CDOUBLE: *(double *)(PyArray_DATA(arr))=*v; break;\
                case NPY_CFLOAT: *(float *)(PyArray_DATA(arr))=*v; break;\
                case NPY_BOOL: *(npy_bool *)(PyArray_DATA(arr))=(*v!=0); break;\
                case NPY_UBYTE: *(unsigned char *)(PyArray_DATA(arr))=*v; break;\
                case NPY_BYTE: *(signed char *)(PyArray_DATA(arr))=*v; break;\
                case NPY_SHORT: *(short *)(PyArray_DATA(arr))=*v; break;\
                case NPY_USHORT: *(npy_ushort *)(PyArray_DATA(arr))=*v; break;\
                case NPY_UINT: *(npy_uint *)(PyArray_DATA(arr))=*v; break;\
                case NPY_ULONG: *(npy_ulong *)(PyArray_DATA(arr))=*v; break;\
                case NPY_LONGLONG: *(npy_longlong *)(PyArray_DATA(arr))=*v; break;\
                case NPY_ULONGLONG: *(npy_ulonglong *)(PyArray_DATA(arr))=*v; break;\
                case NPY_LONGDOUBLE: *(npy_longdouble *)(PyArray_DATA(arr))=*v; break;\
                case NPY_CLONGDOUBLE: *(npy_longdouble *)(PyArray_DATA(arr))=*v; break;\
                case NPY_OBJECT: PyArray_SETITEM(arr, PyArray_DATA(arr), pyobj_from_ ## ctype ## 1(*v)); break;\
        default: return -2;\
        };\
        return 1


/************************ See f2py2e/cfuncs.py: cfuncs ************************/
static int f2py_size(PyArrayObject* var, ...)
{
  npy_int sz = 0;
  npy_int dim;
  npy_int rank;
  va_list argp;
  va_start(argp, var);
  dim = va_arg(argp, npy_int);
  if (dim==-1)
    {
      sz = PyArray_SIZE(var);
    }
  else
    {
      rank = PyArray_NDIM(var);
      if (dim>=1 && dim<=rank)
        sz = PyArray_DIM(var, dim-1);
      else
        fprintf(stderr, "f2py_size: 2nd argument value=%d fails to satisfy 1<=value<=%d. Result will be 0.\n", dim, rank);
    }
  va_end(argp);
  return sz;
}

static int int_from_pyobj(int* v,PyObject *obj,const char *errmess) {
    PyObject* tmp = NULL;
    if (PyInt_Check(obj)) {
        *v = (int)PyInt_AS_LONG(obj);
        return 1;
    }
    tmp = PyNumber_Int(obj);
    if (tmp) {
        *v = PyInt_AS_LONG(tmp);
        Py_DECREF(tmp);
        return 1;
    }
    if (PyComplex_Check(obj))
        tmp = PyObject_GetAttrString(obj,"real");
    else if (PyString_Check(obj) || PyUnicode_Check(obj))
        /*pass*/;
    else if (PySequence_Check(obj))
        tmp = PySequence_GetItem(obj,0);
    if (tmp) {
        PyErr_Clear();
        if (int_from_pyobj(v,tmp,errmess)) {Py_DECREF(tmp); return 1;}
        Py_DECREF(tmp);
    }
    {
        PyObject* err = PyErr_Occurred();
        if (err==NULL) err = gmm_py_error;
        PyErr_SetString(err,errmess);
    }
    return 0;
}

static int try_pyarr_from_double(PyObject* obj,double* v) {
    TRYPYARRAYTEMPLATE(double,'d');
}

static int double_from_pyobj(double* v,PyObject *obj,const char *errmess) {
    PyObject* tmp = NULL;
    if (PyFloat_Check(obj)) {
#ifdef __sgi
        *v = PyFloat_AsDouble(obj);
#else
        *v = PyFloat_AS_DOUBLE(obj);
#endif
        return 1;
    }
    tmp = PyNumber_Float(obj);
    if (tmp) {
#ifdef __sgi
        *v = PyFloat_AsDouble(tmp);
#else
        *v = PyFloat_AS_DOUBLE(tmp);
#endif
        Py_DECREF(tmp);
        return 1;
    }
    if (PyComplex_Check(obj))
        tmp = PyObject_GetAttrString(obj,"real");
    else if (PyString_Check(obj) || PyUnicode_Check(obj))
        /*pass*/;
    else if (PySequence_Check(obj))
        tmp = PySequence_GetItem(obj,0);
    if (tmp) {
        PyErr_Clear();
        if (double_from_pyobj(v,tmp,errmess)) {Py_DECREF(tmp); return 1;}
        Py_DECREF(tmp);
    }
    {
        PyObject* err = PyErr_Occurred();
        if (err==NULL) err = gmm_py_error;
        PyErr_SetString(err,errmess);
    }
    return 0;
}

static int string_from_pyobj(string *str,int *len,const string inistr,PyObject *obj,const char *errmess) {
    PyArrayObject *arr = NULL;
    PyObject *tmp = NULL;
#ifdef DEBUGCFUNCS
fprintf(stderr,"string_from_pyobj(str='%s',len=%d,inistr='%s',obj=%p)\n",(char*)str,*len,(char *)inistr,obj);
#endif
    if (obj == Py_None) {
        if (*len == -1)
            *len = strlen(inistr); /* Will this cause problems? */
        STRINGMALLOC(*str,*len);
        STRINGCOPYN(*str,inistr,*len+1);
        return 1;
    }
    if (PyArray_Check(obj)) {
        if ((arr = (PyArrayObject *)obj) == NULL)
            goto capi_fail;
        if (!ISCONTIGUOUS(arr)) {
            PyErr_SetString(PyExc_ValueError,"array object is non-contiguous.");
            goto capi_fail;
        }
        if (*len == -1)
            *len = (PyArray_ITEMSIZE(arr))*PyArray_SIZE(arr);
        STRINGMALLOC(*str,*len);
        STRINGCOPYN(*str,PyArray_DATA(arr),*len+1);
        return 1;
    }
    if (PyString_Check(obj)) {
        tmp = obj;
        Py_INCREF(tmp);
    }
#if PY_VERSION_HEX >= 0x03000000
    else if (PyUnicode_Check(obj)) {
        tmp = PyUnicode_AsASCIIString(obj);
    }
    else {
        PyObject *tmp2;
        tmp2 = PyObject_Str(obj);
        if (tmp2) {
            tmp = PyUnicode_AsASCIIString(tmp2);
            Py_DECREF(tmp2);
        }
        else {
            tmp = NULL;
        }
    }
#else
    else {
        tmp = PyObject_Str(obj);
    }
#endif
    if (tmp == NULL) goto capi_fail;
    if (*len == -1)
        *len = PyString_GET_SIZE(tmp);
    STRINGMALLOC(*str,*len);
    STRINGCOPYN(*str,PyString_AS_STRING(tmp),*len+1);
    Py_DECREF(tmp);
    return 1;
capi_fail:
    Py_XDECREF(tmp);
    {
        PyObject* err = PyErr_Occurred();
        if (err==NULL) err = gmm_py_error;
        PyErr_SetString(err,errmess);
    }
    return 0;
}


/********************* See f2py2e/cfuncs.py: userincludes *********************/
/*need_userincludes*/

/********************* See f2py2e/capi_rules.py: usercode *********************/


/* See f2py2e/rules.py */
/*eof externroutines*/

/******************** See f2py2e/capi_rules.py: usercode1 ********************/


/******************* See f2py2e/cb_rules.py: buildcallback *******************/
/*need_callbacks*/

/*********************** See f2py2e/rules.py: buildapi ***********************/

/************************************ emn ************************************/
static char doc_f2py_rout_gmm_py_gmm_f2py_module_emn[] = "\
v_emn,error = emn(nstop)\n\nWrapper for ``emn``.\
\n\nParameters\n----------\n"
"nstop : input int\n"
"\nReturns\n-------\n"
"v_emn : rank-1 array('D') with bounds (nstop*(nstop+2))\n"
"error : int";
/*  */
static PyObject *f2py_rout_gmm_py_gmm_f2py_module_emn(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,complex_double*,int*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  int nstop = 0;
  PyObject *nstop_capi = Py_None;
  complex_double *v_emn = NULL;
  npy_intp v_emn_Dims[1] = {-1};
  const int v_emn_Rank = 1;
  PyArrayObject *capi_v_emn_tmp = NULL;
  int capi_v_emn_intent = 0;
  int error = 0;
  static char *capi_kwlist[] = {"nstop",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "O:gmm_py.gmm_f2py_module.emn",\
    capi_kwlist,&nstop_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable nstop */
    f2py_success = int_from_pyobj(&nstop,nstop_capi,"gmm_py.gmm_f2py_module.emn() 1st argument (nstop) can't be converted to int");
  if (f2py_success) {
  /* Processing variable error */
  /* Processing variable v_emn */
  v_emn_Dims[0]=nstop*(nstop+2);
  capi_v_emn_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
  capi_v_emn_tmp = array_from_pyobj(NPY_CDOUBLE,v_emn_Dims,v_emn_Rank,capi_v_emn_intent,Py_None);
  if (capi_v_emn_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(gmm_py_error,"failed in converting hidden `v_emn' of gmm_py.gmm_f2py_module.emn to C/Fortran array" );
  } else {
    v_emn = (complex_double *)(PyArray_DATA(capi_v_emn_tmp));

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(&nstop,v_emn,&error);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("Ni",capi_v_emn_tmp,error);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  }  /*if (capi_v_emn_tmp == NULL) ... else of v_emn*/
  /* End of cleaning variable v_emn */
  /* End of cleaning variable error */
  } /*if (f2py_success) of nstop*/
  /* End of cleaning variable nstop */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/********************************* end of emn *********************************/

/*************************** expansion_coefficients ***************************/
static char doc_f2py_rout_gmm_py_gmm_f2py_module_expansion_coefficients[] = "\
m_coeff,v_cext,v_csca,v_cabs = expansion_coefficients(m_xyz_inp,v_r_inp,m_eps_inp,fint,ref_index,lambda_inp,alpha0,beta0,gamma0,nstop,quasi_static_flag,[ns])\n\nWrapper for ``expansion_coefficients``.\
\n\nParameters\n----------\n"
"m_xyz_inp : input rank-2 array('d') with bounds (ns,3)\n"
"v_r_inp : input rank-1 array('d') with bounds (ns)\n"
"m_eps_inp : input rank-2 array('d') with bounds (ns,2)\n"
"fint : input float\n"
"ref_index : input float\n"
"lambda_inp : in/output rank-0 array(float,'d')\n"
"alpha0 : in/output rank-0 array(float,'d')\n"
"beta0 : in/output rank-0 array(float,'d')\n"
"gamma0 : in/output rank-0 array(float,'d')\n"
"nstop : input int\n"
"quasi_static_flag : input string(len=3)\n"
"\nOther Parameters\n----------------\n"
"ns : input int, optional\n    Default: shape(m_xyz_inp,0)\n"
"\nReturns\n-------\n"
"m_coeff : rank-2 array('D') with bounds (2*nstop*(nstop+2)*ns,2)\n"
"v_cext : rank-1 array('d') with bounds (ns)\n"
"v_csca : rank-1 array('d') with bounds (ns)\n"
"v_cabs : rank-1 array('d') with bounds (ns)";
/*  */
static PyObject *f2py_rout_gmm_py_gmm_f2py_module_expansion_coefficients(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,double*,double*,double*,double*,double*,double*,double*,double*,double*,int*,string,complex_double*,double*,double*,double*,size_t)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  int ns = 0;
  PyObject *ns_capi = Py_None;
  double *m_xyz_inp = NULL;
  npy_intp m_xyz_inp_Dims[2] = {-1, -1};
  const int m_xyz_inp_Rank = 2;
  PyArrayObject *capi_m_xyz_inp_tmp = NULL;
  int capi_m_xyz_inp_intent = 0;
  PyObject *m_xyz_inp_capi = Py_None;
  double *v_r_inp = NULL;
  npy_intp v_r_inp_Dims[1] = {-1};
  const int v_r_inp_Rank = 1;
  PyArrayObject *capi_v_r_inp_tmp = NULL;
  int capi_v_r_inp_intent = 0;
  PyObject *v_r_inp_capi = Py_None;
  double *m_eps_inp = NULL;
  npy_intp m_eps_inp_Dims[2] = {-1, -1};
  const int m_eps_inp_Rank = 2;
  PyArrayObject *capi_m_eps_inp_tmp = NULL;
  int capi_m_eps_inp_intent = 0;
  PyObject *m_eps_inp_capi = Py_None;
  double fint = 0;
  PyObject *fint_capi = Py_None;
  double ref_index = 0;
  PyObject *ref_index_capi = Py_None;
  double lambda_inp = 0;
  PyObject *lambda_inp_capi = Py_None;
  double alpha0 = 0;
  PyObject *alpha0_capi = Py_None;
  double beta0 = 0;
  PyObject *beta0_capi = Py_None;
  double gamma0 = 0;
  PyObject *gamma0_capi = Py_None;
  int nstop = 0;
  PyObject *nstop_capi = Py_None;
  string quasi_static_flag = NULL;
  int slen(quasi_static_flag);
  PyObject *quasi_static_flag_capi = Py_None;
  complex_double *m_coeff = NULL;
  npy_intp m_coeff_Dims[2] = {-1, -1};
  const int m_coeff_Rank = 2;
  PyArrayObject *capi_m_coeff_tmp = NULL;
  int capi_m_coeff_intent = 0;
  double *v_cext = NULL;
  npy_intp v_cext_Dims[1] = {-1};
  const int v_cext_Rank = 1;
  PyArrayObject *capi_v_cext_tmp = NULL;
  int capi_v_cext_intent = 0;
  double *v_csca = NULL;
  npy_intp v_csca_Dims[1] = {-1};
  const int v_csca_Rank = 1;
  PyArrayObject *capi_v_csca_tmp = NULL;
  int capi_v_csca_intent = 0;
  double *v_cabs = NULL;
  npy_intp v_cabs_Dims[1] = {-1};
  const int v_cabs_Rank = 1;
  PyArrayObject *capi_v_cabs_tmp = NULL;
  int capi_v_cabs_intent = 0;
  static char *capi_kwlist[] = {"m_xyz_inp","v_r_inp","m_eps_inp","fint","ref_index","lambda_inp","alpha0","beta0","gamma0","nstop","quasi_static_flag","ns",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOOOOOOOO|O:gmm_py.gmm_f2py_module.expansion_coefficients",\
    capi_kwlist,&m_xyz_inp_capi,&v_r_inp_capi,&m_eps_inp_capi,&fint_capi,&ref_index_capi,&lambda_inp_capi,&alpha0_capi,&beta0_capi,&gamma0_capi,&nstop_capi,&quasi_static_flag_capi,&ns_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable m_xyz_inp */
  m_xyz_inp_Dims[1]=3;
  capi_m_xyz_inp_intent |= F2PY_INTENT_IN;
  capi_m_xyz_inp_tmp = array_from_pyobj(NPY_DOUBLE,m_xyz_inp_Dims,m_xyz_inp_Rank,capi_m_xyz_inp_intent,m_xyz_inp_capi);
  if (capi_m_xyz_inp_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(gmm_py_error,"failed in converting 1st argument `m_xyz_inp' of gmm_py.gmm_f2py_module.expansion_coefficients to C/Fortran array" );
  } else {
    m_xyz_inp = (double *)(PyArray_DATA(capi_m_xyz_inp_tmp));

  /* Processing variable fint */
    f2py_success = double_from_pyobj(&fint,fint_capi,"gmm_py.gmm_f2py_module.expansion_coefficients() 4th argument (fint) can't be converted to double");
  if (f2py_success) {
  /* Processing variable ref_index */
    f2py_success = double_from_pyobj(&ref_index,ref_index_capi,"gmm_py.gmm_f2py_module.expansion_coefficients() 5th argument (ref_index) can't be converted to double");
  if (f2py_success) {
  /* Processing variable lambda_inp */
    f2py_success = double_from_pyobj(&lambda_inp,lambda_inp_capi,"gmm_py.gmm_f2py_module.expansion_coefficients() 6th argument (lambda_inp) can't be converted to double");
  if (f2py_success) {
  /* Processing variable alpha0 */
    f2py_success = double_from_pyobj(&alpha0,alpha0_capi,"gmm_py.gmm_f2py_module.expansion_coefficients() 7th argument (alpha0) can't be converted to double");
  if (f2py_success) {
  /* Processing variable beta0 */
    f2py_success = double_from_pyobj(&beta0,beta0_capi,"gmm_py.gmm_f2py_module.expansion_coefficients() 8th argument (beta0) can't be converted to double");
  if (f2py_success) {
  /* Processing variable gamma0 */
    f2py_success = double_from_pyobj(&gamma0,gamma0_capi,"gmm_py.gmm_f2py_module.expansion_coefficients() 9th argument (gamma0) can't be converted to double");
  if (f2py_success) {
  /* Processing variable nstop */
    f2py_success = int_from_pyobj(&nstop,nstop_capi,"gmm_py.gmm_f2py_module.expansion_coefficients() 10th argument (nstop) can't be converted to int");
  if (f2py_success) {
  /* Processing variable quasi_static_flag */
  slen(quasi_static_flag) = 3;
  f2py_success = string_from_pyobj(&quasi_static_flag,&slen(quasi_static_flag),"",quasi_static_flag_capi,"string_from_pyobj failed in converting 11st argument `quasi_static_flag' of gmm_py.gmm_f2py_module.expansion_coefficients to C string");
  if (f2py_success) {
  /* Processing variable ns */
  if (ns_capi == Py_None) ns = shape(m_xyz_inp,0); else
    f2py_success = int_from_pyobj(&ns,ns_capi,"gmm_py.gmm_f2py_module.expansion_coefficients() 1st keyword (ns) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(shape(m_xyz_inp,0)==ns,"shape(m_xyz_inp,0)==ns","1st keyword ns","expansion_coefficients:ns=%d",ns) {
  /* Processing variable v_r_inp */
  v_r_inp_Dims[0]=ns;
  capi_v_r_inp_intent |= F2PY_INTENT_IN;
  capi_v_r_inp_tmp = array_from_pyobj(NPY_DOUBLE,v_r_inp_Dims,v_r_inp_Rank,capi_v_r_inp_intent,v_r_inp_capi);
  if (capi_v_r_inp_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(gmm_py_error,"failed in converting 2nd argument `v_r_inp' of gmm_py.gmm_f2py_module.expansion_coefficients to C/Fortran array" );
  } else {
    v_r_inp = (double *)(PyArray_DATA(capi_v_r_inp_tmp));

  /* Processing variable m_eps_inp */
  m_eps_inp_Dims[0]=ns,m_eps_inp_Dims[1]=2;
  capi_m_eps_inp_intent |= F2PY_INTENT_IN;
  capi_m_eps_inp_tmp = array_from_pyobj(NPY_DOUBLE,m_eps_inp_Dims,m_eps_inp_Rank,capi_m_eps_inp_intent,m_eps_inp_capi);
  if (capi_m_eps_inp_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(gmm_py_error,"failed in converting 3rd argument `m_eps_inp' of gmm_py.gmm_f2py_module.expansion_coefficients to C/Fortran array" );
  } else {
    m_eps_inp = (double *)(PyArray_DATA(capi_m_eps_inp_tmp));

  /* Processing variable m_coeff */
  m_coeff_Dims[0]=2*nstop*(nstop+2)*ns,m_coeff_Dims[1]=2;
  capi_m_coeff_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
  capi_m_coeff_tmp = array_from_pyobj(NPY_CDOUBLE,m_coeff_Dims,m_coeff_Rank,capi_m_coeff_intent,Py_None);
  if (capi_m_coeff_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(gmm_py_error,"failed in converting hidden `m_coeff' of gmm_py.gmm_f2py_module.expansion_coefficients to C/Fortran array" );
  } else {
    m_coeff = (complex_double *)(PyArray_DATA(capi_m_coeff_tmp));

  /* Processing variable v_cext */
  v_cext_Dims[0]=ns;
  capi_v_cext_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
  capi_v_cext_tmp = array_from_pyobj(NPY_DOUBLE,v_cext_Dims,v_cext_Rank,capi_v_cext_intent,Py_None);
  if (capi_v_cext_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(gmm_py_error,"failed in converting hidden `v_cext' of gmm_py.gmm_f2py_module.expansion_coefficients to C/Fortran array" );
  } else {
    v_cext = (double *)(PyArray_DATA(capi_v_cext_tmp));

  /* Processing variable v_csca */
  v_csca_Dims[0]=ns;
  capi_v_csca_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
  capi_v_csca_tmp = array_from_pyobj(NPY_DOUBLE,v_csca_Dims,v_csca_Rank,capi_v_csca_intent,Py_None);
  if (capi_v_csca_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(gmm_py_error,"failed in converting hidden `v_csca' of gmm_py.gmm_f2py_module.expansion_coefficients to C/Fortran array" );
  } else {
    v_csca = (double *)(PyArray_DATA(capi_v_csca_tmp));

  /* Processing variable v_cabs */
  v_cabs_Dims[0]=ns;
  capi_v_cabs_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
  capi_v_cabs_tmp = array_from_pyobj(NPY_DOUBLE,v_cabs_Dims,v_cabs_Rank,capi_v_cabs_intent,Py_None);
  if (capi_v_cabs_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(gmm_py_error,"failed in converting hidden `v_cabs' of gmm_py.gmm_f2py_module.expansion_coefficients to C/Fortran array" );
  } else {
    v_cabs = (double *)(PyArray_DATA(capi_v_cabs_tmp));

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(&ns,m_xyz_inp,v_r_inp,m_eps_inp,&fint,&ref_index,&lambda_inp,&alpha0,&beta0,&gamma0,&nstop,quasi_static_flag,m_coeff,v_cext,v_csca,v_cabs,slen(quasi_static_flag));
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
  f2py_success = try_pyarr_from_double(lambda_inp_capi,&lambda_inp);
  if (f2py_success) {
  f2py_success = try_pyarr_from_double(alpha0_capi,&alpha0);
  if (f2py_success) {
  f2py_success = try_pyarr_from_double(beta0_capi,&beta0);
  if (f2py_success) {
  f2py_success = try_pyarr_from_double(gamma0_capi,&gamma0);
  if (f2py_success) {
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("NNNN",capi_m_coeff_tmp,capi_v_cext_tmp,capi_v_csca_tmp,capi_v_cabs_tmp);
/*closepyobjfrom*/
  } /*if (f2py_success) of gamma0 pyobjfrom*/
  } /*if (f2py_success) of beta0 pyobjfrom*/
  } /*if (f2py_success) of alpha0 pyobjfrom*/
  } /*if (f2py_success) of lambda_inp pyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  }  /*if (capi_v_cabs_tmp == NULL) ... else of v_cabs*/
  /* End of cleaning variable v_cabs */
  }  /*if (capi_v_csca_tmp == NULL) ... else of v_csca*/
  /* End of cleaning variable v_csca */
  }  /*if (capi_v_cext_tmp == NULL) ... else of v_cext*/
  /* End of cleaning variable v_cext */
  }  /*if (capi_m_coeff_tmp == NULL) ... else of m_coeff*/
  /* End of cleaning variable m_coeff */
  if((PyObject *)capi_m_eps_inp_tmp!=m_eps_inp_capi) {
    Py_XDECREF(capi_m_eps_inp_tmp); }
  }  /*if (capi_m_eps_inp_tmp == NULL) ... else of m_eps_inp*/
  /* End of cleaning variable m_eps_inp */
  if((PyObject *)capi_v_r_inp_tmp!=v_r_inp_capi) {
    Py_XDECREF(capi_v_r_inp_tmp); }
  }  /*if (capi_v_r_inp_tmp == NULL) ... else of v_r_inp*/
  /* End of cleaning variable v_r_inp */
  } /*CHECKSCALAR(shape(m_xyz_inp,0)==ns)*/
  } /*if (f2py_success) of ns*/
  /* End of cleaning variable ns */
    STRINGFREE(quasi_static_flag);
  }  /*if (f2py_success) of quasi_static_flag*/
  /* End of cleaning variable quasi_static_flag */
  } /*if (f2py_success) of nstop*/
  /* End of cleaning variable nstop */
  } /*if (f2py_success) of gamma0*/
  /* End of cleaning variable gamma0 */
  } /*if (f2py_success) of beta0*/
  /* End of cleaning variable beta0 */
  } /*if (f2py_success) of alpha0*/
  /* End of cleaning variable alpha0 */
  } /*if (f2py_success) of lambda_inp*/
  /* End of cleaning variable lambda_inp */
  } /*if (f2py_success) of ref_index*/
  /* End of cleaning variable ref_index */
  } /*if (f2py_success) of fint*/
  /* End of cleaning variable fint */
  if((PyObject *)capi_m_xyz_inp_tmp!=m_xyz_inp_capi) {
    Py_XDECREF(capi_m_xyz_inp_tmp); }
  }  /*if (capi_m_xyz_inp_tmp == NULL) ... else of m_xyz_inp*/
  /* End of cleaning variable m_xyz_inp */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/*********************** end of expansion_coefficients ***********************/

/************************************ exyz ************************************/
static char doc_f2py_rout_gmm_py_gmm_f2py_module_exyz[] = "\
ex,ey,ez,eabs,error = exyz(flaginc,nstop,ratio,lambda_inp,alpha0,beta0,gamma0,x,y,z,v_amnbmn,v_dmncmn,v_emn,m_xyz_inp,m_eps_inp,v_r_inp,ref_index,quasi_static_flag,[ns])\n\nWrapper for ``exyz``.\
\n\nParameters\n----------\n"
"flaginc : input string(len=3)\n"
"nstop : input int\n"
"ratio : input int\n"
"lambda_inp : in/output rank-0 array(float,'d')\n"
"alpha0 : input float\n"
"beta0 : input float\n"
"gamma0 : input float\n"
"x : input float\n"
"y : input float\n"
"z : input float\n"
"v_amnbmn : input rank-1 array('D') with bounds (2*nstop*(nstop+2)*ns)\n"
"v_dmncmn : input rank-1 array('D') with bounds (2*nstop*(nstop+2)*ns)\n"
"v_emn : input rank-1 array('D') with bounds (nstop*(nstop+2))\n"
"m_xyz_inp : input rank-2 array('d') with bounds (ns,3)\n"
"m_eps_inp : input rank-2 array('d') with bounds (ns,2)\n"
"v_r_inp : input rank-1 array('d') with bounds (ns)\n"
"ref_index : input float\n"
"quasi_static_flag : input string(len=3)\n"
"\nOther Parameters\n----------------\n"
"ns : input int, optional\n    Default: shape(m_xyz_inp,0)\n"
"\nReturns\n-------\n"
"ex : complex\n"
"ey : complex\n"
"ez : complex\n"
"eabs : float\n"
"error : int";
/*  */
static PyObject *f2py_rout_gmm_py_gmm_f2py_module_exyz(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(string,int*,int*,int*,double*,double*,double*,double*,double*,double*,double*,complex_double*,complex_double*,complex_double*,double*,double*,double*,double*,string,complex_double*,complex_double*,complex_double*,double*,int*,size_t,size_t)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  string flaginc = NULL;
  int slen(flaginc);
  PyObject *flaginc_capi = Py_None;
  int ns = 0;
  PyObject *ns_capi = Py_None;
  int nstop = 0;
  PyObject *nstop_capi = Py_None;
  int ratio = 0;
  PyObject *ratio_capi = Py_None;
  double lambda_inp = 0;
  PyObject *lambda_inp_capi = Py_None;
  double alpha0 = 0;
  PyObject *alpha0_capi = Py_None;
  double beta0 = 0;
  PyObject *beta0_capi = Py_None;
  double gamma0 = 0;
  PyObject *gamma0_capi = Py_None;
  double x = 0;
  PyObject *x_capi = Py_None;
  double y = 0;
  PyObject *y_capi = Py_None;
  double z = 0;
  PyObject *z_capi = Py_None;
  complex_double *v_amnbmn = NULL;
  npy_intp v_amnbmn_Dims[1] = {-1};
  const int v_amnbmn_Rank = 1;
  PyArrayObject *capi_v_amnbmn_tmp = NULL;
  int capi_v_amnbmn_intent = 0;
  PyObject *v_amnbmn_capi = Py_None;
  complex_double *v_dmncmn = NULL;
  npy_intp v_dmncmn_Dims[1] = {-1};
  const int v_dmncmn_Rank = 1;
  PyArrayObject *capi_v_dmncmn_tmp = NULL;
  int capi_v_dmncmn_intent = 0;
  PyObject *v_dmncmn_capi = Py_None;
  complex_double *v_emn = NULL;
  npy_intp v_emn_Dims[1] = {-1};
  const int v_emn_Rank = 1;
  PyArrayObject *capi_v_emn_tmp = NULL;
  int capi_v_emn_intent = 0;
  PyObject *v_emn_capi = Py_None;
  double *m_xyz_inp = NULL;
  npy_intp m_xyz_inp_Dims[2] = {-1, -1};
  const int m_xyz_inp_Rank = 2;
  PyArrayObject *capi_m_xyz_inp_tmp = NULL;
  int capi_m_xyz_inp_intent = 0;
  PyObject *m_xyz_inp_capi = Py_None;
  double *m_eps_inp = NULL;
  npy_intp m_eps_inp_Dims[2] = {-1, -1};
  const int m_eps_inp_Rank = 2;
  PyArrayObject *capi_m_eps_inp_tmp = NULL;
  int capi_m_eps_inp_intent = 0;
  PyObject *m_eps_inp_capi = Py_None;
  double *v_r_inp = NULL;
  npy_intp v_r_inp_Dims[1] = {-1};
  const int v_r_inp_Rank = 1;
  PyArrayObject *capi_v_r_inp_tmp = NULL;
  int capi_v_r_inp_intent = 0;
  PyObject *v_r_inp_capi = Py_None;
  double ref_index = 0;
  PyObject *ref_index_capi = Py_None;
  string quasi_static_flag = NULL;
  int slen(quasi_static_flag);
  PyObject *quasi_static_flag_capi = Py_None;
  complex_double ex;
  PyObject *ex_capi = Py_None;
  complex_double ey;
  PyObject *ey_capi = Py_None;
  complex_double ez;
  PyObject *ez_capi = Py_None;
  double eabs = 0;
  int error = 0;
  static char *capi_kwlist[] = {"flaginc","nstop","ratio","lambda_inp","alpha0","beta0","gamma0","x","y","z","v_amnbmn","v_dmncmn","v_emn","m_xyz_inp","m_eps_inp","v_r_inp","ref_index","quasi_static_flag","ns",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOOOOOOOOOOOOOOO|O:gmm_py.gmm_f2py_module.exyz",\
    capi_kwlist,&flaginc_capi,&nstop_capi,&ratio_capi,&lambda_inp_capi,&alpha0_capi,&beta0_capi,&gamma0_capi,&x_capi,&y_capi,&z_capi,&v_amnbmn_capi,&v_dmncmn_capi,&v_emn_capi,&m_xyz_inp_capi,&m_eps_inp_capi,&v_r_inp_capi,&ref_index_capi,&quasi_static_flag_capi,&ns_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable flaginc */
  slen(flaginc) = 3;
  f2py_success = string_from_pyobj(&flaginc,&slen(flaginc),"",flaginc_capi,"string_from_pyobj failed in converting 1st argument `flaginc' of gmm_py.gmm_f2py_module.exyz to C string");
  if (f2py_success) {
  /* Processing variable nstop */
    f2py_success = int_from_pyobj(&nstop,nstop_capi,"gmm_py.gmm_f2py_module.exyz() 2nd argument (nstop) can't be converted to int");
  if (f2py_success) {
  /* Processing variable ratio */
    f2py_success = int_from_pyobj(&ratio,ratio_capi,"gmm_py.gmm_f2py_module.exyz() 3rd argument (ratio) can't be converted to int");
  if (f2py_success) {
  /* Processing variable lambda_inp */
    f2py_success = double_from_pyobj(&lambda_inp,lambda_inp_capi,"gmm_py.gmm_f2py_module.exyz() 4th argument (lambda_inp) can't be converted to double");
  if (f2py_success) {
  /* Processing variable alpha0 */
    f2py_success = double_from_pyobj(&alpha0,alpha0_capi,"gmm_py.gmm_f2py_module.exyz() 5th argument (alpha0) can't be converted to double");
  if (f2py_success) {
  /* Processing variable beta0 */
    f2py_success = double_from_pyobj(&beta0,beta0_capi,"gmm_py.gmm_f2py_module.exyz() 6th argument (beta0) can't be converted to double");
  if (f2py_success) {
  /* Processing variable gamma0 */
    f2py_success = double_from_pyobj(&gamma0,gamma0_capi,"gmm_py.gmm_f2py_module.exyz() 7th argument (gamma0) can't be converted to double");
  if (f2py_success) {
  /* Processing variable x */
    f2py_success = double_from_pyobj(&x,x_capi,"gmm_py.gmm_f2py_module.exyz() 8th argument (x) can't be converted to double");
  if (f2py_success) {
  /* Processing variable y */
    f2py_success = double_from_pyobj(&y,y_capi,"gmm_py.gmm_f2py_module.exyz() 9th argument (y) can't be converted to double");
  if (f2py_success) {
  /* Processing variable z */
    f2py_success = double_from_pyobj(&z,z_capi,"gmm_py.gmm_f2py_module.exyz() 10th argument (z) can't be converted to double");
  if (f2py_success) {
  /* Processing variable m_xyz_inp */
  m_xyz_inp_Dims[1]=3;
  capi_m_xyz_inp_intent |= F2PY_INTENT_IN;
  capi_m_xyz_inp_tmp = array_from_pyobj(NPY_DOUBLE,m_xyz_inp_Dims,m_xyz_inp_Rank,capi_m_xyz_inp_intent,m_xyz_inp_capi);
  if (capi_m_xyz_inp_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(gmm_py_error,"failed in converting 14th argument `m_xyz_inp' of gmm_py.gmm_f2py_module.exyz to C/Fortran array" );
  } else {
    m_xyz_inp = (double *)(PyArray_DATA(capi_m_xyz_inp_tmp));

  /* Processing variable ref_index */
    f2py_success = double_from_pyobj(&ref_index,ref_index_capi,"gmm_py.gmm_f2py_module.exyz() 17th argument (ref_index) can't be converted to double");
  if (f2py_success) {
  /* Processing variable quasi_static_flag */
  slen(quasi_static_flag) = 3;
  f2py_success = string_from_pyobj(&quasi_static_flag,&slen(quasi_static_flag),"",quasi_static_flag_capi,"string_from_pyobj failed in converting 18th argument `quasi_static_flag' of gmm_py.gmm_f2py_module.exyz to C string");
  if (f2py_success) {
  /* Processing variable ex */
  /* Processing variable ey */
  /* Processing variable ez */
  /* Processing variable eabs */
  /* Processing variable error */
  /* Processing variable ns */
  if (ns_capi == Py_None) ns = shape(m_xyz_inp,0); else
    f2py_success = int_from_pyobj(&ns,ns_capi,"gmm_py.gmm_f2py_module.exyz() 1st keyword (ns) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(shape(m_xyz_inp,0)==ns,"shape(m_xyz_inp,0)==ns","1st keyword ns","exyz:ns=%d",ns) {
  /* Processing variable v_amnbmn */
  v_amnbmn_Dims[0]=2*nstop*(nstop+2)*ns;
  capi_v_amnbmn_intent |= F2PY_INTENT_IN;
  capi_v_amnbmn_tmp = array_from_pyobj(NPY_CDOUBLE,v_amnbmn_Dims,v_amnbmn_Rank,capi_v_amnbmn_intent,v_amnbmn_capi);
  if (capi_v_amnbmn_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(gmm_py_error,"failed in converting 11st argument `v_amnbmn' of gmm_py.gmm_f2py_module.exyz to C/Fortran array" );
  } else {
    v_amnbmn = (complex_double *)(PyArray_DATA(capi_v_amnbmn_tmp));

  /* Processing variable v_dmncmn */
  v_dmncmn_Dims[0]=2*nstop*(nstop+2)*ns;
  capi_v_dmncmn_intent |= F2PY_INTENT_IN;
  capi_v_dmncmn_tmp = array_from_pyobj(NPY_CDOUBLE,v_dmncmn_Dims,v_dmncmn_Rank,capi_v_dmncmn_intent,v_dmncmn_capi);
  if (capi_v_dmncmn_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(gmm_py_error,"failed in converting 12nd argument `v_dmncmn' of gmm_py.gmm_f2py_module.exyz to C/Fortran array" );
  } else {
    v_dmncmn = (complex_double *)(PyArray_DATA(capi_v_dmncmn_tmp));

  /* Processing variable v_emn */
  v_emn_Dims[0]=nstop*(nstop+2);
  capi_v_emn_intent |= F2PY_INTENT_IN;
  capi_v_emn_tmp = array_from_pyobj(NPY_CDOUBLE,v_emn_Dims,v_emn_Rank,capi_v_emn_intent,v_emn_capi);
  if (capi_v_emn_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(gmm_py_error,"failed in converting 13rd argument `v_emn' of gmm_py.gmm_f2py_module.exyz to C/Fortran array" );
  } else {
    v_emn = (complex_double *)(PyArray_DATA(capi_v_emn_tmp));

  /* Processing variable m_eps_inp */
  m_eps_inp_Dims[0]=ns,m_eps_inp_Dims[1]=2;
  capi_m_eps_inp_intent |= F2PY_INTENT_IN;
  capi_m_eps_inp_tmp = array_from_pyobj(NPY_DOUBLE,m_eps_inp_Dims,m_eps_inp_Rank,capi_m_eps_inp_intent,m_eps_inp_capi);
  if (capi_m_eps_inp_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(gmm_py_error,"failed in converting 15th argument `m_eps_inp' of gmm_py.gmm_f2py_module.exyz to C/Fortran array" );
  } else {
    m_eps_inp = (double *)(PyArray_DATA(capi_m_eps_inp_tmp));

  /* Processing variable v_r_inp */
  v_r_inp_Dims[0]=ns;
  capi_v_r_inp_intent |= F2PY_INTENT_IN;
  capi_v_r_inp_tmp = array_from_pyobj(NPY_DOUBLE,v_r_inp_Dims,v_r_inp_Rank,capi_v_r_inp_intent,v_r_inp_capi);
  if (capi_v_r_inp_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(gmm_py_error,"failed in converting 16th argument `v_r_inp' of gmm_py.gmm_f2py_module.exyz to C/Fortran array" );
  } else {
    v_r_inp = (double *)(PyArray_DATA(capi_v_r_inp_tmp));

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(flaginc,&ns,&nstop,&ratio,&lambda_inp,&alpha0,&beta0,&gamma0,&x,&y,&z,v_amnbmn,v_dmncmn,v_emn,m_xyz_inp,m_eps_inp,v_r_inp,&ref_index,quasi_static_flag,&ex,&ey,&ez,&eabs,&error,slen(flaginc),slen(quasi_static_flag));
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
  f2py_success = try_pyarr_from_double(lambda_inp_capi,&lambda_inp);
  if (f2py_success) {
  ex_capi = pyobj_from_complex_double1(ex);
  ey_capi = pyobj_from_complex_double1(ey);
  ez_capi = pyobj_from_complex_double1(ez);
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("NNNdi",ex_capi,ey_capi,ez_capi,eabs,error);
/*closepyobjfrom*/
  } /*if (f2py_success) of lambda_inp pyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  if((PyObject *)capi_v_r_inp_tmp!=v_r_inp_capi) {
    Py_XDECREF(capi_v_r_inp_tmp); }
  }  /*if (capi_v_r_inp_tmp == NULL) ... else of v_r_inp*/
  /* End of cleaning variable v_r_inp */
  if((PyObject *)capi_m_eps_inp_tmp!=m_eps_inp_capi) {
    Py_XDECREF(capi_m_eps_inp_tmp); }
  }  /*if (capi_m_eps_inp_tmp == NULL) ... else of m_eps_inp*/
  /* End of cleaning variable m_eps_inp */
  if((PyObject *)capi_v_emn_tmp!=v_emn_capi) {
    Py_XDECREF(capi_v_emn_tmp); }
  }  /*if (capi_v_emn_tmp == NULL) ... else of v_emn*/
  /* End of cleaning variable v_emn */
  if((PyObject *)capi_v_dmncmn_tmp!=v_dmncmn_capi) {
    Py_XDECREF(capi_v_dmncmn_tmp); }
  }  /*if (capi_v_dmncmn_tmp == NULL) ... else of v_dmncmn*/
  /* End of cleaning variable v_dmncmn */
  if((PyObject *)capi_v_amnbmn_tmp!=v_amnbmn_capi) {
    Py_XDECREF(capi_v_amnbmn_tmp); }
  }  /*if (capi_v_amnbmn_tmp == NULL) ... else of v_amnbmn*/
  /* End of cleaning variable v_amnbmn */
  } /*CHECKSCALAR(shape(m_xyz_inp,0)==ns)*/
  } /*if (f2py_success) of ns*/
  /* End of cleaning variable ns */
  /* End of cleaning variable error */
  /* End of cleaning variable eabs */
  /* End of cleaning variable ez */
  /* End of cleaning variable ey */
  /* End of cleaning variable ex */
    STRINGFREE(quasi_static_flag);
  }  /*if (f2py_success) of quasi_static_flag*/
  /* End of cleaning variable quasi_static_flag */
  } /*if (f2py_success) of ref_index*/
  /* End of cleaning variable ref_index */
  if((PyObject *)capi_m_xyz_inp_tmp!=m_xyz_inp_capi) {
    Py_XDECREF(capi_m_xyz_inp_tmp); }
  }  /*if (capi_m_xyz_inp_tmp == NULL) ... else of m_xyz_inp*/
  /* End of cleaning variable m_xyz_inp */
  } /*if (f2py_success) of z*/
  /* End of cleaning variable z */
  } /*if (f2py_success) of y*/
  /* End of cleaning variable y */
  } /*if (f2py_success) of x*/
  /* End of cleaning variable x */
  } /*if (f2py_success) of gamma0*/
  /* End of cleaning variable gamma0 */
  } /*if (f2py_success) of beta0*/
  /* End of cleaning variable beta0 */
  } /*if (f2py_success) of alpha0*/
  /* End of cleaning variable alpha0 */
  } /*if (f2py_success) of lambda_inp*/
  /* End of cleaning variable lambda_inp */
  } /*if (f2py_success) of ratio*/
  /* End of cleaning variable ratio */
  } /*if (f2py_success) of nstop*/
  /* End of cleaning variable nstop */
    STRINGFREE(flaginc);
  }  /*if (f2py_success) of flaginc*/
  /* End of cleaning variable flaginc */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/******************************** end of exyz ********************************/

/************************************ efar ************************************/
static char doc_f2py_rout_gmm_py_gmm_f2py_module_efar[] = "\
m_sc,scatot,error = efar(k,nstop,phimin,phimax,phistep,thetastep,betap,v_amnbmn,m_xyz_inp,[ns])\n\nWrapper for ``efar``.\
\n\nParameters\n----------\n"
"k : input float\n"
"nstop : input int\n"
"phimin : input float\n"
"phimax : input float\n"
"phistep : input int\n"
"thetastep : input int\n"
"betap : in/output rank-0 array(float,'d')\n"
"v_amnbmn : input rank-1 array('D') with bounds (2*nstop*(nstop+2)*ns)\n"
"m_xyz_inp : input rank-2 array('d') with bounds (ns,3)\n"
"\nOther Parameters\n----------------\n"
"ns : input int, optional\n    Default: shape(m_xyz_inp,0)\n"
"\nReturns\n-------\n"
"m_sc : rank-3 array('D') with bounds (thetastep + 1,phistep + 1,7)\n"
"scatot : float\n"
"error : int";
/*  */
static PyObject *f2py_rout_gmm_py_gmm_f2py_module_efar(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(double*,int*,int*,double*,double*,int*,int*,double*,complex_double*,double*,complex_double*,double*,int*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  double k = 0;
  PyObject *k_capi = Py_None;
  int ns = 0;
  PyObject *ns_capi = Py_None;
  int nstop = 0;
  PyObject *nstop_capi = Py_None;
  double phimin = 0;
  PyObject *phimin_capi = Py_None;
  double phimax = 0;
  PyObject *phimax_capi = Py_None;
  int phistep = 0;
  PyObject *phistep_capi = Py_None;
  int thetastep = 0;
  PyObject *thetastep_capi = Py_None;
  double betap = 0;
  PyObject *betap_capi = Py_None;
  complex_double *v_amnbmn = NULL;
  npy_intp v_amnbmn_Dims[1] = {-1};
  const int v_amnbmn_Rank = 1;
  PyArrayObject *capi_v_amnbmn_tmp = NULL;
  int capi_v_amnbmn_intent = 0;
  PyObject *v_amnbmn_capi = Py_None;
  double *m_xyz_inp = NULL;
  npy_intp m_xyz_inp_Dims[2] = {-1, -1};
  const int m_xyz_inp_Rank = 2;
  PyArrayObject *capi_m_xyz_inp_tmp = NULL;
  int capi_m_xyz_inp_intent = 0;
  PyObject *m_xyz_inp_capi = Py_None;
  complex_double *m_sc = NULL;
  npy_intp m_sc_Dims[3] = {-1, -1, -1};
  const int m_sc_Rank = 3;
  PyArrayObject *capi_m_sc_tmp = NULL;
  int capi_m_sc_intent = 0;
  double scatot = 0;
  int error = 0;
  static char *capi_kwlist[] = {"k","nstop","phimin","phimax","phistep","thetastep","betap","v_amnbmn","m_xyz_inp","ns",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOOOOOO|O:gmm_py.gmm_f2py_module.efar",\
    capi_kwlist,&k_capi,&nstop_capi,&phimin_capi,&phimax_capi,&phistep_capi,&thetastep_capi,&betap_capi,&v_amnbmn_capi,&m_xyz_inp_capi,&ns_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable k */
    f2py_success = double_from_pyobj(&k,k_capi,"gmm_py.gmm_f2py_module.efar() 1st argument (k) can't be converted to double");
  if (f2py_success) {
  /* Processing variable nstop */
    f2py_success = int_from_pyobj(&nstop,nstop_capi,"gmm_py.gmm_f2py_module.efar() 2nd argument (nstop) can't be converted to int");
  if (f2py_success) {
  /* Processing variable phimin */
    f2py_success = double_from_pyobj(&phimin,phimin_capi,"gmm_py.gmm_f2py_module.efar() 3rd argument (phimin) can't be converted to double");
  if (f2py_success) {
  /* Processing variable phimax */
    f2py_success = double_from_pyobj(&phimax,phimax_capi,"gmm_py.gmm_f2py_module.efar() 4th argument (phimax) can't be converted to double");
  if (f2py_success) {
  /* Processing variable phistep */
    f2py_success = int_from_pyobj(&phistep,phistep_capi,"gmm_py.gmm_f2py_module.efar() 5th argument (phistep) can't be converted to int");
  if (f2py_success) {
  /* Processing variable thetastep */
    f2py_success = int_from_pyobj(&thetastep,thetastep_capi,"gmm_py.gmm_f2py_module.efar() 6th argument (thetastep) can't be converted to int");
  if (f2py_success) {
  /* Processing variable betap */
    f2py_success = double_from_pyobj(&betap,betap_capi,"gmm_py.gmm_f2py_module.efar() 7th argument (betap) can't be converted to double");
  if (f2py_success) {
  /* Processing variable m_xyz_inp */
  m_xyz_inp_Dims[1]=3;
  capi_m_xyz_inp_intent |= F2PY_INTENT_IN;
  capi_m_xyz_inp_tmp = array_from_pyobj(NPY_DOUBLE,m_xyz_inp_Dims,m_xyz_inp_Rank,capi_m_xyz_inp_intent,m_xyz_inp_capi);
  if (capi_m_xyz_inp_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(gmm_py_error,"failed in converting 9th argument `m_xyz_inp' of gmm_py.gmm_f2py_module.efar to C/Fortran array" );
  } else {
    m_xyz_inp = (double *)(PyArray_DATA(capi_m_xyz_inp_tmp));

  /* Processing variable scatot */
  /* Processing variable error */
  /* Processing variable ns */
  if (ns_capi == Py_None) ns = shape(m_xyz_inp,0); else
    f2py_success = int_from_pyobj(&ns,ns_capi,"gmm_py.gmm_f2py_module.efar() 1st keyword (ns) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(shape(m_xyz_inp,0)==ns,"shape(m_xyz_inp,0)==ns","1st keyword ns","efar:ns=%d",ns) {
  /* Processing variable v_amnbmn */
  v_amnbmn_Dims[0]=2*nstop*(nstop+2)*ns;
  capi_v_amnbmn_intent |= F2PY_INTENT_IN;
  capi_v_amnbmn_tmp = array_from_pyobj(NPY_CDOUBLE,v_amnbmn_Dims,v_amnbmn_Rank,capi_v_amnbmn_intent,v_amnbmn_capi);
  if (capi_v_amnbmn_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(gmm_py_error,"failed in converting 8th argument `v_amnbmn' of gmm_py.gmm_f2py_module.efar to C/Fortran array" );
  } else {
    v_amnbmn = (complex_double *)(PyArray_DATA(capi_v_amnbmn_tmp));

  /* Processing variable m_sc */
  m_sc_Dims[0]=thetastep + 1,m_sc_Dims[1]=phistep + 1,m_sc_Dims[2]=7;
  capi_m_sc_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
  capi_m_sc_tmp = array_from_pyobj(NPY_CDOUBLE,m_sc_Dims,m_sc_Rank,capi_m_sc_intent,Py_None);
  if (capi_m_sc_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(gmm_py_error,"failed in converting hidden `m_sc' of gmm_py.gmm_f2py_module.efar to C/Fortran array" );
  } else {
    m_sc = (complex_double *)(PyArray_DATA(capi_m_sc_tmp));

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(&k,&ns,&nstop,&phimin,&phimax,&phistep,&thetastep,&betap,v_amnbmn,m_xyz_inp,m_sc,&scatot,&error);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
  f2py_success = try_pyarr_from_double(betap_capi,&betap);
  if (f2py_success) {
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("Ndi",capi_m_sc_tmp,scatot,error);
/*closepyobjfrom*/
  } /*if (f2py_success) of betap pyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  }  /*if (capi_m_sc_tmp == NULL) ... else of m_sc*/
  /* End of cleaning variable m_sc */
  if((PyObject *)capi_v_amnbmn_tmp!=v_amnbmn_capi) {
    Py_XDECREF(capi_v_amnbmn_tmp); }
  }  /*if (capi_v_amnbmn_tmp == NULL) ... else of v_amnbmn*/
  /* End of cleaning variable v_amnbmn */
  } /*CHECKSCALAR(shape(m_xyz_inp,0)==ns)*/
  } /*if (f2py_success) of ns*/
  /* End of cleaning variable ns */
  /* End of cleaning variable error */
  /* End of cleaning variable scatot */
  if((PyObject *)capi_m_xyz_inp_tmp!=m_xyz_inp_capi) {
    Py_XDECREF(capi_m_xyz_inp_tmp); }
  }  /*if (capi_m_xyz_inp_tmp == NULL) ... else of m_xyz_inp*/
  /* End of cleaning variable m_xyz_inp */
  } /*if (f2py_success) of betap*/
  /* End of cleaning variable betap */
  } /*if (f2py_success) of thetastep*/
  /* End of cleaning variable thetastep */
  } /*if (f2py_success) of phistep*/
  /* End of cleaning variable phistep */
  } /*if (f2py_success) of phimax*/
  /* End of cleaning variable phimax */
  } /*if (f2py_success) of phimin*/
  /* End of cleaning variable phimin */
  } /*if (f2py_success) of nstop*/
  /* End of cleaning variable nstop */
  } /*if (f2py_success) of k*/
  /* End of cleaning variable k */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/******************************** end of efar ********************************/

/******************************* efar_poynting *******************************/
static char doc_f2py_rout_gmm_py_gmm_f2py_module_efar_poynting[] = "\
m_sc,scatot,error = efar_poynting(k,nstop,phimin,phimax,phistep,thetastep,betap,v_amnbmn,m_xyz_inp,[ns])\n\nWrapper for ``efar_poynting``.\
\n\nParameters\n----------\n"
"k : input float\n"
"nstop : input int\n"
"phimin : input float\n"
"phimax : input float\n"
"phistep : input int\n"
"thetastep : input int\n"
"betap : in/output rank-0 array(float,'d')\n"
"v_amnbmn : input rank-1 array('D') with bounds (2*nstop*(nstop+2)*ns)\n"
"m_xyz_inp : input rank-2 array('d') with bounds (ns,3)\n"
"\nOther Parameters\n----------------\n"
"ns : input int, optional\n    Default: shape(m_xyz_inp,0)\n"
"\nReturns\n-------\n"
"m_sc : rank-3 array('D') with bounds (thetastep + 1,phistep + 1,7)\n"
"scatot : float\n"
"error : int";
/*  */
static PyObject *f2py_rout_gmm_py_gmm_f2py_module_efar_poynting(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(double*,int*,int*,double*,double*,int*,int*,double*,complex_double*,double*,complex_double*,double*,int*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  double k = 0;
  PyObject *k_capi = Py_None;
  int ns = 0;
  PyObject *ns_capi = Py_None;
  int nstop = 0;
  PyObject *nstop_capi = Py_None;
  double phimin = 0;
  PyObject *phimin_capi = Py_None;
  double phimax = 0;
  PyObject *phimax_capi = Py_None;
  int phistep = 0;
  PyObject *phistep_capi = Py_None;
  int thetastep = 0;
  PyObject *thetastep_capi = Py_None;
  double betap = 0;
  PyObject *betap_capi = Py_None;
  complex_double *v_amnbmn = NULL;
  npy_intp v_amnbmn_Dims[1] = {-1};
  const int v_amnbmn_Rank = 1;
  PyArrayObject *capi_v_amnbmn_tmp = NULL;
  int capi_v_amnbmn_intent = 0;
  PyObject *v_amnbmn_capi = Py_None;
  double *m_xyz_inp = NULL;
  npy_intp m_xyz_inp_Dims[2] = {-1, -1};
  const int m_xyz_inp_Rank = 2;
  PyArrayObject *capi_m_xyz_inp_tmp = NULL;
  int capi_m_xyz_inp_intent = 0;
  PyObject *m_xyz_inp_capi = Py_None;
  complex_double *m_sc = NULL;
  npy_intp m_sc_Dims[3] = {-1, -1, -1};
  const int m_sc_Rank = 3;
  PyArrayObject *capi_m_sc_tmp = NULL;
  int capi_m_sc_intent = 0;
  double scatot = 0;
  int error = 0;
  static char *capi_kwlist[] = {"k","nstop","phimin","phimax","phistep","thetastep","betap","v_amnbmn","m_xyz_inp","ns",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOOOOOO|O:gmm_py.gmm_f2py_module.efar_poynting",\
    capi_kwlist,&k_capi,&nstop_capi,&phimin_capi,&phimax_capi,&phistep_capi,&thetastep_capi,&betap_capi,&v_amnbmn_capi,&m_xyz_inp_capi,&ns_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable k */
    f2py_success = double_from_pyobj(&k,k_capi,"gmm_py.gmm_f2py_module.efar_poynting() 1st argument (k) can't be converted to double");
  if (f2py_success) {
  /* Processing variable nstop */
    f2py_success = int_from_pyobj(&nstop,nstop_capi,"gmm_py.gmm_f2py_module.efar_poynting() 2nd argument (nstop) can't be converted to int");
  if (f2py_success) {
  /* Processing variable phimin */
    f2py_success = double_from_pyobj(&phimin,phimin_capi,"gmm_py.gmm_f2py_module.efar_poynting() 3rd argument (phimin) can't be converted to double");
  if (f2py_success) {
  /* Processing variable phimax */
    f2py_success = double_from_pyobj(&phimax,phimax_capi,"gmm_py.gmm_f2py_module.efar_poynting() 4th argument (phimax) can't be converted to double");
  if (f2py_success) {
  /* Processing variable phistep */
    f2py_success = int_from_pyobj(&phistep,phistep_capi,"gmm_py.gmm_f2py_module.efar_poynting() 5th argument (phistep) can't be converted to int");
  if (f2py_success) {
  /* Processing variable thetastep */
    f2py_success = int_from_pyobj(&thetastep,thetastep_capi,"gmm_py.gmm_f2py_module.efar_poynting() 6th argument (thetastep) can't be converted to int");
  if (f2py_success) {
  /* Processing variable betap */
    f2py_success = double_from_pyobj(&betap,betap_capi,"gmm_py.gmm_f2py_module.efar_poynting() 7th argument (betap) can't be converted to double");
  if (f2py_success) {
  /* Processing variable m_xyz_inp */
  m_xyz_inp_Dims[1]=3;
  capi_m_xyz_inp_intent |= F2PY_INTENT_IN;
  capi_m_xyz_inp_tmp = array_from_pyobj(NPY_DOUBLE,m_xyz_inp_Dims,m_xyz_inp_Rank,capi_m_xyz_inp_intent,m_xyz_inp_capi);
  if (capi_m_xyz_inp_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(gmm_py_error,"failed in converting 9th argument `m_xyz_inp' of gmm_py.gmm_f2py_module.efar_poynting to C/Fortran array" );
  } else {
    m_xyz_inp = (double *)(PyArray_DATA(capi_m_xyz_inp_tmp));

  /* Processing variable scatot */
  /* Processing variable error */
  /* Processing variable ns */
  if (ns_capi == Py_None) ns = shape(m_xyz_inp,0); else
    f2py_success = int_from_pyobj(&ns,ns_capi,"gmm_py.gmm_f2py_module.efar_poynting() 1st keyword (ns) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(shape(m_xyz_inp,0)==ns,"shape(m_xyz_inp,0)==ns","1st keyword ns","efar_poynting:ns=%d",ns) {
  /* Processing variable v_amnbmn */
  v_amnbmn_Dims[0]=2*nstop*(nstop+2)*ns;
  capi_v_amnbmn_intent |= F2PY_INTENT_IN;
  capi_v_amnbmn_tmp = array_from_pyobj(NPY_CDOUBLE,v_amnbmn_Dims,v_amnbmn_Rank,capi_v_amnbmn_intent,v_amnbmn_capi);
  if (capi_v_amnbmn_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(gmm_py_error,"failed in converting 8th argument `v_amnbmn' of gmm_py.gmm_f2py_module.efar_poynting to C/Fortran array" );
  } else {
    v_amnbmn = (complex_double *)(PyArray_DATA(capi_v_amnbmn_tmp));

  /* Processing variable m_sc */
  m_sc_Dims[0]=thetastep + 1,m_sc_Dims[1]=phistep + 1,m_sc_Dims[2]=7;
  capi_m_sc_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
  capi_m_sc_tmp = array_from_pyobj(NPY_CDOUBLE,m_sc_Dims,m_sc_Rank,capi_m_sc_intent,Py_None);
  if (capi_m_sc_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(gmm_py_error,"failed in converting hidden `m_sc' of gmm_py.gmm_f2py_module.efar_poynting to C/Fortran array" );
  } else {
    m_sc = (complex_double *)(PyArray_DATA(capi_m_sc_tmp));

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(&k,&ns,&nstop,&phimin,&phimax,&phistep,&thetastep,&betap,v_amnbmn,m_xyz_inp,m_sc,&scatot,&error);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
  f2py_success = try_pyarr_from_double(betap_capi,&betap);
  if (f2py_success) {
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("Ndi",capi_m_sc_tmp,scatot,error);
/*closepyobjfrom*/
  } /*if (f2py_success) of betap pyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  }  /*if (capi_m_sc_tmp == NULL) ... else of m_sc*/
  /* End of cleaning variable m_sc */
  if((PyObject *)capi_v_amnbmn_tmp!=v_amnbmn_capi) {
    Py_XDECREF(capi_v_amnbmn_tmp); }
  }  /*if (capi_v_amnbmn_tmp == NULL) ... else of v_amnbmn*/
  /* End of cleaning variable v_amnbmn */
  } /*CHECKSCALAR(shape(m_xyz_inp,0)==ns)*/
  } /*if (f2py_success) of ns*/
  /* End of cleaning variable ns */
  /* End of cleaning variable error */
  /* End of cleaning variable scatot */
  if((PyObject *)capi_m_xyz_inp_tmp!=m_xyz_inp_capi) {
    Py_XDECREF(capi_m_xyz_inp_tmp); }
  }  /*if (capi_m_xyz_inp_tmp == NULL) ... else of m_xyz_inp*/
  /* End of cleaning variable m_xyz_inp */
  } /*if (f2py_success) of betap*/
  /* End of cleaning variable betap */
  } /*if (f2py_success) of thetastep*/
  /* End of cleaning variable thetastep */
  } /*if (f2py_success) of phistep*/
  /* End of cleaning variable phistep */
  } /*if (f2py_success) of phimax*/
  /* End of cleaning variable phimax */
  } /*if (f2py_success) of phimin*/
  /* End of cleaning variable phimin */
  } /*if (f2py_success) of nstop*/
  /* End of cleaning variable nstop */
  } /*if (f2py_success) of k*/
  /* End of cleaning variable k */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/**************************** end of efar_poynting ****************************/

/****************************** dip_coefficients ******************************/
static char doc_f2py_rout_gmm_py_gmm_f2py_module_dip_coefficients[] = "\
m_coeff,v_w = dip_coefficients(ndip,m_xyz_inp,v_r_inp,m_eps_inp,fint,q0,ref_index,lambda_inp,alpha0,beta0,gamma0,nstop,quasi_static_flag,[ns])\n\nWrapper for ``dip_coefficients``.\
\n\nParameters\n----------\n"
"ndip : input int\n"
"m_xyz_inp : input rank-2 array('d') with bounds (ns,3)\n"
"v_r_inp : input rank-1 array('d') with bounds (ns)\n"
"m_eps_inp : input rank-2 array('d') with bounds (ns,2)\n"
"fint : input float\n"
"q0 : input float\n"
"ref_index : input float\n"
"lambda_inp : in/output rank-0 array(float,'d')\n"
"alpha0 : in/output rank-0 array(float,'d')\n"
"beta0 : in/output rank-0 array(float,'d')\n"
"gamma0 : in/output rank-0 array(float,'d')\n"
"nstop : input int\n"
"quasi_static_flag : input string(len=3)\n"
"\nOther Parameters\n----------------\n"
"ns : input int, optional\n    Default: shape(m_xyz_inp,0)\n"
"\nReturns\n-------\n"
"m_coeff : rank-2 array('D') with bounds (2*nstop*(nstop+2)*ns,2)\n"
"v_w : rank-1 array('d') with bounds (6)";
/*  */
static PyObject *f2py_rout_gmm_py_gmm_f2py_module_dip_coefficients(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,int*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,int*,string,complex_double*,double*,size_t)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  int ns = 0;
  PyObject *ns_capi = Py_None;
  int ndip = 0;
  PyObject *ndip_capi = Py_None;
  double *m_xyz_inp = NULL;
  npy_intp m_xyz_inp_Dims[2] = {-1, -1};
  const int m_xyz_inp_Rank = 2;
  PyArrayObject *capi_m_xyz_inp_tmp = NULL;
  int capi_m_xyz_inp_intent = 0;
  PyObject *m_xyz_inp_capi = Py_None;
  double *v_r_inp = NULL;
  npy_intp v_r_inp_Dims[1] = {-1};
  const int v_r_inp_Rank = 1;
  PyArrayObject *capi_v_r_inp_tmp = NULL;
  int capi_v_r_inp_intent = 0;
  PyObject *v_r_inp_capi = Py_None;
  double *m_eps_inp = NULL;
  npy_intp m_eps_inp_Dims[2] = {-1, -1};
  const int m_eps_inp_Rank = 2;
  PyArrayObject *capi_m_eps_inp_tmp = NULL;
  int capi_m_eps_inp_intent = 0;
  PyObject *m_eps_inp_capi = Py_None;
  double fint = 0;
  PyObject *fint_capi = Py_None;
  double q0 = 0;
  PyObject *q0_capi = Py_None;
  double ref_index = 0;
  PyObject *ref_index_capi = Py_None;
  double lambda_inp = 0;
  PyObject *lambda_inp_capi = Py_None;
  double alpha0 = 0;
  PyObject *alpha0_capi = Py_None;
  double beta0 = 0;
  PyObject *beta0_capi = Py_None;
  double gamma0 = 0;
  PyObject *gamma0_capi = Py_None;
  int nstop = 0;
  PyObject *nstop_capi = Py_None;
  string quasi_static_flag = NULL;
  int slen(quasi_static_flag);
  PyObject *quasi_static_flag_capi = Py_None;
  complex_double *m_coeff = NULL;
  npy_intp m_coeff_Dims[2] = {-1, -1};
  const int m_coeff_Rank = 2;
  PyArrayObject *capi_m_coeff_tmp = NULL;
  int capi_m_coeff_intent = 0;
  double *v_w = NULL;
  npy_intp v_w_Dims[1] = {-1};
  const int v_w_Rank = 1;
  PyArrayObject *capi_v_w_tmp = NULL;
  int capi_v_w_intent = 0;
  static char *capi_kwlist[] = {"ndip","m_xyz_inp","v_r_inp","m_eps_inp","fint","q0","ref_index","lambda_inp","alpha0","beta0","gamma0","nstop","quasi_static_flag","ns",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOOOOOOOOOO|O:gmm_py.gmm_f2py_module.dip_coefficients",\
    capi_kwlist,&ndip_capi,&m_xyz_inp_capi,&v_r_inp_capi,&m_eps_inp_capi,&fint_capi,&q0_capi,&ref_index_capi,&lambda_inp_capi,&alpha0_capi,&beta0_capi,&gamma0_capi,&nstop_capi,&quasi_static_flag_capi,&ns_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable ndip */
    f2py_success = int_from_pyobj(&ndip,ndip_capi,"gmm_py.gmm_f2py_module.dip_coefficients() 1st argument (ndip) can't be converted to int");
  if (f2py_success) {
  /* Processing variable m_xyz_inp */
  m_xyz_inp_Dims[1]=3;
  capi_m_xyz_inp_intent |= F2PY_INTENT_IN;
  capi_m_xyz_inp_tmp = array_from_pyobj(NPY_DOUBLE,m_xyz_inp_Dims,m_xyz_inp_Rank,capi_m_xyz_inp_intent,m_xyz_inp_capi);
  if (capi_m_xyz_inp_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(gmm_py_error,"failed in converting 2nd argument `m_xyz_inp' of gmm_py.gmm_f2py_module.dip_coefficients to C/Fortran array" );
  } else {
    m_xyz_inp = (double *)(PyArray_DATA(capi_m_xyz_inp_tmp));

  /* Processing variable fint */
    f2py_success = double_from_pyobj(&fint,fint_capi,"gmm_py.gmm_f2py_module.dip_coefficients() 5th argument (fint) can't be converted to double");
  if (f2py_success) {
  /* Processing variable q0 */
    f2py_success = double_from_pyobj(&q0,q0_capi,"gmm_py.gmm_f2py_module.dip_coefficients() 6th argument (q0) can't be converted to double");
  if (f2py_success) {
  /* Processing variable ref_index */
    f2py_success = double_from_pyobj(&ref_index,ref_index_capi,"gmm_py.gmm_f2py_module.dip_coefficients() 7th argument (ref_index) can't be converted to double");
  if (f2py_success) {
  /* Processing variable lambda_inp */
    f2py_success = double_from_pyobj(&lambda_inp,lambda_inp_capi,"gmm_py.gmm_f2py_module.dip_coefficients() 8th argument (lambda_inp) can't be converted to double");
  if (f2py_success) {
  /* Processing variable alpha0 */
    f2py_success = double_from_pyobj(&alpha0,alpha0_capi,"gmm_py.gmm_f2py_module.dip_coefficients() 9th argument (alpha0) can't be converted to double");
  if (f2py_success) {
  /* Processing variable beta0 */
    f2py_success = double_from_pyobj(&beta0,beta0_capi,"gmm_py.gmm_f2py_module.dip_coefficients() 10th argument (beta0) can't be converted to double");
  if (f2py_success) {
  /* Processing variable gamma0 */
    f2py_success = double_from_pyobj(&gamma0,gamma0_capi,"gmm_py.gmm_f2py_module.dip_coefficients() 11st argument (gamma0) can't be converted to double");
  if (f2py_success) {
  /* Processing variable nstop */
    f2py_success = int_from_pyobj(&nstop,nstop_capi,"gmm_py.gmm_f2py_module.dip_coefficients() 12nd argument (nstop) can't be converted to int");
  if (f2py_success) {
  /* Processing variable quasi_static_flag */
  slen(quasi_static_flag) = 3;
  f2py_success = string_from_pyobj(&quasi_static_flag,&slen(quasi_static_flag),"",quasi_static_flag_capi,"string_from_pyobj failed in converting 13rd argument `quasi_static_flag' of gmm_py.gmm_f2py_module.dip_coefficients to C string");
  if (f2py_success) {
  /* Processing variable v_w */
  v_w_Dims[0]=6;
  capi_v_w_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
  capi_v_w_tmp = array_from_pyobj(NPY_DOUBLE,v_w_Dims,v_w_Rank,capi_v_w_intent,Py_None);
  if (capi_v_w_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(gmm_py_error,"failed in converting hidden `v_w' of gmm_py.gmm_f2py_module.dip_coefficients to C/Fortran array" );
  } else {
    v_w = (double *)(PyArray_DATA(capi_v_w_tmp));

  /* Processing variable ns */
  if (ns_capi == Py_None) ns = shape(m_xyz_inp,0); else
    f2py_success = int_from_pyobj(&ns,ns_capi,"gmm_py.gmm_f2py_module.dip_coefficients() 1st keyword (ns) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(shape(m_xyz_inp,0)==ns,"shape(m_xyz_inp,0)==ns","1st keyword ns","dip_coefficients:ns=%d",ns) {
  /* Processing variable v_r_inp */
  v_r_inp_Dims[0]=ns;
  capi_v_r_inp_intent |= F2PY_INTENT_IN;
  capi_v_r_inp_tmp = array_from_pyobj(NPY_DOUBLE,v_r_inp_Dims,v_r_inp_Rank,capi_v_r_inp_intent,v_r_inp_capi);
  if (capi_v_r_inp_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(gmm_py_error,"failed in converting 3rd argument `v_r_inp' of gmm_py.gmm_f2py_module.dip_coefficients to C/Fortran array" );
  } else {
    v_r_inp = (double *)(PyArray_DATA(capi_v_r_inp_tmp));

  /* Processing variable m_eps_inp */
  m_eps_inp_Dims[0]=ns,m_eps_inp_Dims[1]=2;
  capi_m_eps_inp_intent |= F2PY_INTENT_IN;
  capi_m_eps_inp_tmp = array_from_pyobj(NPY_DOUBLE,m_eps_inp_Dims,m_eps_inp_Rank,capi_m_eps_inp_intent,m_eps_inp_capi);
  if (capi_m_eps_inp_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(gmm_py_error,"failed in converting 4th argument `m_eps_inp' of gmm_py.gmm_f2py_module.dip_coefficients to C/Fortran array" );
  } else {
    m_eps_inp = (double *)(PyArray_DATA(capi_m_eps_inp_tmp));

  /* Processing variable m_coeff */
  m_coeff_Dims[0]=2*nstop*(nstop+2)*ns,m_coeff_Dims[1]=2;
  capi_m_coeff_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
  capi_m_coeff_tmp = array_from_pyobj(NPY_CDOUBLE,m_coeff_Dims,m_coeff_Rank,capi_m_coeff_intent,Py_None);
  if (capi_m_coeff_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(gmm_py_error,"failed in converting hidden `m_coeff' of gmm_py.gmm_f2py_module.dip_coefficients to C/Fortran array" );
  } else {
    m_coeff = (complex_double *)(PyArray_DATA(capi_m_coeff_tmp));

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(&ns,&ndip,m_xyz_inp,v_r_inp,m_eps_inp,&fint,&q0,&ref_index,&lambda_inp,&alpha0,&beta0,&gamma0,&nstop,quasi_static_flag,m_coeff,v_w,slen(quasi_static_flag));
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
  f2py_success = try_pyarr_from_double(lambda_inp_capi,&lambda_inp);
  if (f2py_success) {
  f2py_success = try_pyarr_from_double(alpha0_capi,&alpha0);
  if (f2py_success) {
  f2py_success = try_pyarr_from_double(beta0_capi,&beta0);
  if (f2py_success) {
  f2py_success = try_pyarr_from_double(gamma0_capi,&gamma0);
  if (f2py_success) {
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("NN",capi_m_coeff_tmp,capi_v_w_tmp);
/*closepyobjfrom*/
  } /*if (f2py_success) of gamma0 pyobjfrom*/
  } /*if (f2py_success) of beta0 pyobjfrom*/
  } /*if (f2py_success) of alpha0 pyobjfrom*/
  } /*if (f2py_success) of lambda_inp pyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  }  /*if (capi_m_coeff_tmp == NULL) ... else of m_coeff*/
  /* End of cleaning variable m_coeff */
  if((PyObject *)capi_m_eps_inp_tmp!=m_eps_inp_capi) {
    Py_XDECREF(capi_m_eps_inp_tmp); }
  }  /*if (capi_m_eps_inp_tmp == NULL) ... else of m_eps_inp*/
  /* End of cleaning variable m_eps_inp */
  if((PyObject *)capi_v_r_inp_tmp!=v_r_inp_capi) {
    Py_XDECREF(capi_v_r_inp_tmp); }
  }  /*if (capi_v_r_inp_tmp == NULL) ... else of v_r_inp*/
  /* End of cleaning variable v_r_inp */
  } /*CHECKSCALAR(shape(m_xyz_inp,0)==ns)*/
  } /*if (f2py_success) of ns*/
  /* End of cleaning variable ns */
  }  /*if (capi_v_w_tmp == NULL) ... else of v_w*/
  /* End of cleaning variable v_w */
    STRINGFREE(quasi_static_flag);
  }  /*if (f2py_success) of quasi_static_flag*/
  /* End of cleaning variable quasi_static_flag */
  } /*if (f2py_success) of nstop*/
  /* End of cleaning variable nstop */
  } /*if (f2py_success) of gamma0*/
  /* End of cleaning variable gamma0 */
  } /*if (f2py_success) of beta0*/
  /* End of cleaning variable beta0 */
  } /*if (f2py_success) of alpha0*/
  /* End of cleaning variable alpha0 */
  } /*if (f2py_success) of lambda_inp*/
  /* End of cleaning variable lambda_inp */
  } /*if (f2py_success) of ref_index*/
  /* End of cleaning variable ref_index */
  } /*if (f2py_success) of q0*/
  /* End of cleaning variable q0 */
  } /*if (f2py_success) of fint*/
  /* End of cleaning variable fint */
  if((PyObject *)capi_m_xyz_inp_tmp!=m_xyz_inp_capi) {
    Py_XDECREF(capi_m_xyz_inp_tmp); }
  }  /*if (capi_m_xyz_inp_tmp == NULL) ... else of m_xyz_inp*/
  /* End of cleaning variable m_xyz_inp */
  } /*if (f2py_success) of ndip*/
  /* End of cleaning variable ndip */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/************************** end of dip_coefficients **************************/
/*eof body*/

/******************* See f2py2e/f90mod_rules.py: buildhooks *******************/

static FortranDataDef f2py_local_kinds_def[] = {
  {"sgl",0,{{-1}},NPY_INT},
  {"dbl",0,{{-1}},NPY_INT},
  {"vshort",0,{{-1}},NPY_INT},
  {"short",0,{{-1}},NPY_INT},
  {"long",0,{{-1}},NPY_INT},
  {"lo",0,{{-1}},NPY_INT},
  {"length",0,{{-1}},NPY_INT},
  {"pi",0,{{-1}},NPY_FLOAT},
  {"pio2",0,{{-1}},NPY_FLOAT},
  {"twopi",0,{{-1}},NPY_FLOAT},
  {"sqrt2",0,{{-1}},NPY_FLOAT},
  {"euler",0,{{-1}},NPY_FLOAT},
  {"pi_d",0,{{-1}},NPY_DOUBLE},
  {"pio2_d",0,{{-1}},NPY_DOUBLE},
  {"twopi_d",0,{{-1}},NPY_DOUBLE},
  {"sqrt2_d",0,{{-1}},NPY_DOUBLE},
  {"euler_d",0,{{-1}},NPY_DOUBLE},
  {"e",0,{{-1}},NPY_DOUBLE},
  {"me",0,{{-1}},NPY_DOUBLE},
  {"e0",0,{{-1}},NPY_DOUBLE},
  {"c",0,{{-1}},NPY_DOUBLE},
  {"zerodbl",0,{{-1}},NPY_DOUBLE},
  {NULL}
};

static void f2py_setup_local_kinds(char *sgl,char *dbl,char *vshort,char *short_bn,char *long_bn,char *lo,char *length,char *pi,char *pio2,char *twopi,char *sqrt2,char *euler,char *pi_d,char *pio2_d,char *twopi_d,char *sqrt2_d,char *euler_d,char *e,char *me,char *e0,char *c,char *zerodbl) {
  int i_f2py=0;
  f2py_local_kinds_def[i_f2py++].data = sgl;
  f2py_local_kinds_def[i_f2py++].data = dbl;
  f2py_local_kinds_def[i_f2py++].data = vshort;
  f2py_local_kinds_def[i_f2py++].data = short_bn;
  f2py_local_kinds_def[i_f2py++].data = long_bn;
  f2py_local_kinds_def[i_f2py++].data = lo;
  f2py_local_kinds_def[i_f2py++].data = length;
  f2py_local_kinds_def[i_f2py++].data = pi;
  f2py_local_kinds_def[i_f2py++].data = pio2;
  f2py_local_kinds_def[i_f2py++].data = twopi;
  f2py_local_kinds_def[i_f2py++].data = sqrt2;
  f2py_local_kinds_def[i_f2py++].data = euler;
  f2py_local_kinds_def[i_f2py++].data = pi_d;
  f2py_local_kinds_def[i_f2py++].data = pio2_d;
  f2py_local_kinds_def[i_f2py++].data = twopi_d;
  f2py_local_kinds_def[i_f2py++].data = sqrt2_d;
  f2py_local_kinds_def[i_f2py++].data = euler_d;
  f2py_local_kinds_def[i_f2py++].data = e;
  f2py_local_kinds_def[i_f2py++].data = me;
  f2py_local_kinds_def[i_f2py++].data = e0;
  f2py_local_kinds_def[i_f2py++].data = c;
  f2py_local_kinds_def[i_f2py++].data = zerodbl;
}
extern void F_FUNC_US(f2pyinitlocal_kinds,F2PYINITLOCAL_KINDS)(void (*)(char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*));
static void f2py_init_local_kinds(void) {
  F_FUNC_US(f2pyinitlocal_kinds,F2PYINITLOCAL_KINDS)(f2py_setup_local_kinds);
}


static FortranDataDef f2py_gmm_f2py_module_def[] = {
  {"emn",-1,{{-1}},0,NULL,(void *)f2py_rout_gmm_py_gmm_f2py_module_emn,doc_f2py_rout_gmm_py_gmm_f2py_module_emn},
  {"expansion_coefficients",-1,{{-1}},0,NULL,(void *)f2py_rout_gmm_py_gmm_f2py_module_expansion_coefficients,doc_f2py_rout_gmm_py_gmm_f2py_module_expansion_coefficients},
  {"exyz",-1,{{-1}},0,NULL,(void *)f2py_rout_gmm_py_gmm_f2py_module_exyz,doc_f2py_rout_gmm_py_gmm_f2py_module_exyz},
  {"efar",-1,{{-1}},0,NULL,(void *)f2py_rout_gmm_py_gmm_f2py_module_efar,doc_f2py_rout_gmm_py_gmm_f2py_module_efar},
  {"efar_poynting",-1,{{-1}},0,NULL,(void *)f2py_rout_gmm_py_gmm_f2py_module_efar_poynting,doc_f2py_rout_gmm_py_gmm_f2py_module_efar_poynting},
  {"dip_coefficients",-1,{{-1}},0,NULL,(void *)f2py_rout_gmm_py_gmm_f2py_module_dip_coefficients,doc_f2py_rout_gmm_py_gmm_f2py_module_dip_coefficients},
  {NULL}
};

static void f2py_setup_gmm_f2py_module(char *emn,char *expansion_coefficients,char *exyz,char *efar,char *efar_poynting,char *dip_coefficients) {
  int i_f2py=0;
  f2py_gmm_f2py_module_def[i_f2py++].data = emn;
  f2py_gmm_f2py_module_def[i_f2py++].data = expansion_coefficients;
  f2py_gmm_f2py_module_def[i_f2py++].data = exyz;
  f2py_gmm_f2py_module_def[i_f2py++].data = efar;
  f2py_gmm_f2py_module_def[i_f2py++].data = efar_poynting;
  f2py_gmm_f2py_module_def[i_f2py++].data = dip_coefficients;
}
extern void F_FUNC_US(f2pyinitgmm_f2py_module,F2PYINITGMM_F2PY_MODULE)(void (*)(char *,char *,char *,char *,char *,char *));
static void f2py_init_gmm_f2py_module(void) {
  F_FUNC_US(f2pyinitgmm_f2py_module,F2PYINITGMM_F2PY_MODULE)(f2py_setup_gmm_f2py_module);
}

/*need_f90modhooks*/

/************** See f2py2e/rules.py: module_rules['modulebody'] **************/

/******************* See f2py2e/common_rules.py: buildhooks *******************/

/*need_commonhooks*/

/**************************** See f2py2e/rules.py ****************************/

static FortranDataDef f2py_routine_defs[] = {

/*eof routine_defs*/
  {NULL}
};

static PyMethodDef f2py_module_methods[] = {

  {NULL,NULL}
};

#if PY_VERSION_HEX >= 0x03000000
static struct PyModuleDef moduledef = {
  PyModuleDef_HEAD_INIT,
  "gmm_py",
  NULL,
  -1,
  f2py_module_methods,
  NULL,
  NULL,
  NULL,
  NULL
};
#endif

#if PY_VERSION_HEX >= 0x03000000
#define RETVAL m
PyMODINIT_FUNC PyInit_gmm_py(void) {
#else
#define RETVAL
PyMODINIT_FUNC initgmm_py(void) {
#endif
  int i;
  PyObject *m,*d, *s;
#if PY_VERSION_HEX >= 0x03000000
  m = gmm_py_module = PyModule_Create(&moduledef);
#else
  m = gmm_py_module = Py_InitModule("gmm_py", f2py_module_methods);
#endif
  Py_TYPE(&PyFortran_Type) = &PyType_Type;
  import_array();
  if (PyErr_Occurred())
    {PyErr_SetString(PyExc_ImportError, "can't initialize module gmm_py (failed to import numpy)"); return RETVAL;}
  d = PyModule_GetDict(m);
  s = PyString_FromString("$Revision: $");
  PyDict_SetItemString(d, "__version__", s);
#if PY_VERSION_HEX >= 0x03000000
  s = PyUnicode_FromString(
#else
  s = PyString_FromString(
#endif
    "This module 'gmm_py' is auto-generated with f2py (version:2).\nFunctions:\n"
"Fortran 90/95 modules:\n""  local_kinds --- sgl,dbl,vshort,short,long,lo,length,pi,pio2,twopi,sqrt2,euler,pi_d,pio2_d,twopi_d,sqrt2_d,euler_d,e,me,e0,c,zerodbl""  gmm_f2py_module --- emn(),expansion_coefficients(),exyz(),efar(),efar_poynting(),dip_coefficients()"".");
  PyDict_SetItemString(d, "__doc__", s);
  gmm_py_error = PyErr_NewException ("gmm_py.error", NULL, NULL);
  Py_DECREF(s);
  for(i=0;f2py_routine_defs[i].name!=NULL;i++)
    PyDict_SetItemString(d, f2py_routine_defs[i].name,PyFortranObject_NewAsAttr(&f2py_routine_defs[i]));






/*eof initf2pywraphooks*/
  PyDict_SetItemString(d, "gmm_f2py_module", PyFortranObject_New(f2py_gmm_f2py_module_def,f2py_init_gmm_f2py_module));
  PyDict_SetItemString(d, "local_kinds", PyFortranObject_New(f2py_local_kinds_def,f2py_init_local_kinds));
/*eof initf90modhooks*/

/*eof initcommonhooks*/


#ifdef F2PY_REPORT_ATEXIT
  if (! PyErr_Occurred())
    on_exit(f2py_report_on_exit,(void*)"gmm_py");
#endif

  return RETVAL;
}
#ifdef __cplusplus
}
#endif
